### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by quasipedia** [christianalfoni/EmptyBox#16]
Judging from Christian's blog (haven't downloaded/installed the app myself), the RSS feed feature is broken, returning an empty feed instead of a list of the most recent posts. You can try W3' validation service here:

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.christianalfoni.com%2Frss

And it will say that:

```
line 23, column 12: XML parsing error: <unknown>:23:12: unbound prefix
```

**Comment by christianalfoni** [comment]
Hi @quasipedia and thanks for the report! I believe RSS apps handles this, I have not gotten any reports on it not working, though have gotten reports that it does work :-)

**Comment by quasipedia** [comment]
Hi Christian!

And congrats/thank you for all the wonderful work you do, and the instructive posts you write! [ Ok, off-topic, yet... thank you! ] :)

I am happy to hear that at least somebody manages to read your feed, but I hope you will agree that the fact that some (definitively not mine though!) RSS readers gets around a broken feed, shouldn't be a reason not to fix something that does not comply with the standard specifications... or otherwise I shall suggest a wonderful browser coded in Redmond, which is entirely built around that idea... :trollface:  ;)

Also: maybe (or maybe not, who knows!) this may explain why your blog pages aren't at the top of the search results for libraries that you maintain... RSS feeds are one of the ingredients that get thrown in the mix by SE in their ranking algos! :o

Best regards and thank you again for all your excellent insights!

**Comment by christianalfoni** [comment]
Ah, so it is not working? hehe.. then I will of course fix it :-)

And thanks for bringing it to my attention!

And thanks for the feedback! :-)

**Comment by christianalfoni** [comment]
Could you try now? :-)

**Comment by quasipedia** [comment]
```
        _
       /(|
      (  :
     __\  \  _____
   (____)  `|
  (____)|   |
   (____).__|
    (___)__.|_____
```
