### ISSUE TITLE
As a visitor I want to see a short description of an article

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/EmptyBox#5]

**Comment by bebraw** [comment]
How do you plan to deal with this? One way would to be to deal with this via metadata and a configurable rule. Example:

``` markdown
---
shortDescription: "Short description goes here"
---
...
```

``` javascript
// in configuration you would have a rule for this
module.exports = {
    getMeta: function(meta) {
        return merge(meta, {
            shortDescription: meta.content.split('').slice(0, 20).join(' ') + '...',
        });
    },
};
```

`getMeta` is something that would be executed per page. It doesn't have to be defined, by default it uses just the defaults. As you can see from the example, it allows you to shape metadata content. This means you could generate short descriptions based on content and so on.

**Comment by christianalfoni** [comment]
Hi @bebraw ,

Yeah, that is a way to go, though I want the writing of an article to be as pure as possible. So I think I will start with parsing out some text, like:

``` markdown
# Some header
Writing some stuff
```

Just grab the text from the first paragraph. 

That said, if more article configuration is needed I think your idea is great :-) that is how it works in Jekyll too.
